on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env: 
      NBA_API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install moto
          pip install pytest
      - name: Run tests with pytest\
        run: pytest --junitxml=pytest-report.xml
      - name: Pack Lambda
        run: |
          mkdir -p main
          cp src/main.py main/
          # Install dependencies into the package folder
          pip install -r requirements.txt -t main/
          # Zip the Lambda function
          cd main
          zip -r ../main.zip .
      - name: Configure AWS credentials from repo
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}  
          aws-region: us-east-1
          role-session-name: GitHubActionSession
      - name: Deploy Lambda Function to AWS
        run: |
          FUNCTION_NAME="devops_day02_lambda"
          aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip
          aws lambda update-function-configuration --function-name $FUNCTION_NAME --environment "Variables={NBA_API_KEY=${{ secrets.API_KEY }},SNS_TOPIC_ARN=${{ secrets.SNS_TOPIC_ARN }}}"